# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 5 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: damoklov
google_analytics: damoklov
title: damoklov

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: damoklov

description: Personal Blog
author:
  name: Mykhailo Pazyniuk
  email: mishanya@protonmail.com
  github: damoklov
  twitter: damoklov_
  pinterest: null
  linkedin: pazyniuk
  bio: Security Engineer • CTIA
  email_md5: 42ac6055af81efcf131ce97c734eda13

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html
sidebar_background_image: https://www.dropbox.com/s/krg9z6e8ozd21hk/boards.jpg?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
